name: flutter_pet_app
description: A pet-raising task management app based on flow theory and I(M;E) model
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.0
  intl: ^0.17.0
  path_provider: ^2.1.2
  dio: ^5.4.3
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  crypto: ^3.0.3
  device_info_plus: ^9.1.0
  uuid: ^4.2.1
  fluttertoast: ^8.2.4
  provider: ^6.1.1
  audioplayers: ^5.2.1
  http: ^1.2.0
  fl_chart: ^0.68.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/avatars/
    - assets/images/pets/
    - assets/images/evolutions/
